before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: UONqakqFiy/J21ufYgbBsiEIVdRiIUR97cYqKFbS1CvOUTVKMYL4RuTVvBtAfBf+kfo4BBu1a6ViVlBTE9+6Cu5Ud6qakgjK6HFsdiWMMl5RyG9Mm237egvIeKCfgUvYjWQLu9buFOdFwTUPw/gyoIgBJPMAo0T2rm988plCwY4L8egNZdDU/mjlhyGrANRSSAPWLBEjAEEwHGyvnMtXF7m204qHtFQH5P2IZXfu6rNTxcHmPK9BPfZ/rR9GsIJe0m8h0s3+Y86c2Qz7yukDIopHWsnw5CCwWXYUvdxXI3ao8qiFAutdC037DVOpmEZ1BhAx8r0AN7KqRrRxrZZfgT9CL6KKFcxF0LykrC9f+nHx19Lm6p/ONK4TCZ1AOF6/DmIcbNSzp2XaqiAPGI6JlQz6JwhMQujBIMkou9QDCNje8u+axmTVCW1d6+X6ODLSUI8td4cO+9r/9hY2WoByPy5kBoZ6xHcdbCzJ7J1SE3cSEJYuVYu+uYvAnR9GTMVfOjjQbkscU7m9aTO/ub3ZFhNkhc7BFKCwKidN9Scz78qkHG7+7yJt8UFnP4zCJjTm9UEVvGSneh7f39AxhgOQjY2NKm8PoGPSMzU/C/uMq4HzmkVO06hFE7jkptDzogBSK5vYJtuPCpevYWlgOXLY7IVR8Iv+gDqupBsr4JmybnI= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
